# NumPy exercises

We are going to practice NumPy skills and basic syntax.

We put here also some examples that were not in the tutorial on purpose. Try to use google and offial NumPy documentation to solve these exercises.

#### 1. Import the numpy package under the name `np` (★☆☆)

In [1]:
import numpy as np

#### 2. Create a null vector of size 10 (★☆☆)

In [3]:
null = np.zeros(10)
null

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 3.  Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [4]:
null[4] = 1
null

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

#### 4.  Create a vector with values ranging from 10 to 49 (★☆☆)

In [11]:
vector = np.random.randint(10, 49, size = (1,3))
vector

array([[47, 25, 20]])

#### 5.  Reverse a vector (first element becomes last) (★☆☆)

In [15]:
vector = np.array([1,2,3,4])
reverse_vector = vector[::-1]
reverse_vector

array([4, 3, 2, 1])

#### 6.  Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [16]:
a = np.random.randint(8, size = (3,3))
a

array([[1, 0, 5],
       [7, 2, 1],
       [2, 0, 5]])

#### 7. Find indices of non-zero elements from \[1,2,0,0,4,0\] (★☆☆)

In [17]:
a = np.array([1,2,0,0,4,0])
np.nonzero(a)

(array([0, 1, 4], dtype=int64),)

#### 8. Create a 3x3x3 array with random values (★☆☆)

In [18]:
a = np.random.rand(3,3,3)
a

array([[[9.11503418e-01, 1.94252178e-01, 5.26207468e-01],
        [9.97048312e-01, 9.70309866e-01, 4.41966711e-01],
        [5.43339763e-01, 5.53000393e-01, 7.70643108e-01]],

       [[3.64139367e-02, 3.00982821e-01, 4.00384473e-01],
        [1.24252635e-01, 2.63315578e-01, 8.50946311e-01],
        [5.19617409e-02, 5.06665279e-01, 6.93414654e-01]],

       [[8.99288533e-01, 5.12253833e-01, 7.29543343e-01],
        [5.87481953e-01, 7.77905964e-01, 6.54855922e-01],
        [6.09337892e-01, 3.72353716e-04, 6.00788059e-01]]])

#### 9. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [20]:
a = np.random.randint(100, size = (10,10))
a

array([[ 1, 53, 66,  0, 75, 49, 80, 97, 35, 64],
       [ 0, 60,  3, 56, 84, 50, 56, 52, 86, 76],
       [89, 20, 40, 83, 49, 39, 26, 15, 37, 37],
       [60,  2, 84, 61, 42, 67, 50, 48, 55, 78],
       [92, 72, 85, 87, 82, 18, 25, 51, 77, 24],
       [83, 27, 55, 99, 29, 17, 17, 55, 94, 98],
       [94,  2, 14, 16, 63, 45, 41,  8, 94, 94],
       [19,  2, 36, 31,  0, 14, 48, 73, 30, 30],
       [85,  2, 73, 77, 94, 69, 29, 43, 50, 76],
       [55, 63, 14, 15, 59, 48, 40,  0, 85, 47]])

In [21]:
np.min(a)

0

In [22]:
np.max(a)

99

#### 10. Create a random vector of size 30 and find the mean value (★☆☆)

In [23]:
vector = np.random.randint(100, size = (1,30))
vector

array([[69, 10, 55, 49, 71, 86, 81, 16, 58, 70,  7, 15, 87, 72, 44, 88,
        10, 42,  3,  6, 26, 96, 29, 70, 20, 40,  2, 49, 53,  8]])

In [24]:
np.mean(vector)

44.4

#### 11. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [26]:
a = np.ones((3,3))
a

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [27]:
b = np.array([0])
a[1,1] = b
a

array([[1., 1., 1.],
       [1., 0., 1.],
       [1., 1., 1.]])

#### 12. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [29]:
a = np.pad(a, pad_width = 1, mode = 'constant', constant_values = 0)
a
# Looked this one up

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 1., 1., 0., 0.],
       [0., 0., 1., 0., 1., 0., 0.],
       [0., 0., 1., 1., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

#### 13. What is the result of the following expression? (★☆☆)

```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

0  -- nan, 
True -- False, 
True -- False (neither are actual numbers?), 
0 -- nan, 
True -- True, 
True -- False (order of operations?), 

In [30]:
0 * np.nan

nan

In [31]:
np.nan == np.nan

False

In [32]:
np.inf > np.nan

False

In [33]:
np.nan - np.nan

nan

In [34]:
np.nan in set([np.nan])

True

In [35]:
0.3 == 3 * 0.1

False

#### 14. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [36]:
# Looked this up
a = np.diag(1 + np.arange(4), k = -1)
a

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

#### 15. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [40]:
print(np.unravel_index(100, (6,7,8)))

(1, 5, 4)


#### 16. Normalize a 5x5 random matrix (★☆☆)

In [42]:
#Looked up
a = np.random.random((5,5))
amax, amin = a.max(), a.min()
a = (a - amin) / (amax - amin)
print(a)

[[0.         0.22288421 0.91814853 0.56761408 0.19559653]
 [0.71615641 0.42446274 0.59624977 0.1838499  0.59502433]
 [0.15902279 0.9648544  0.85088289 0.2345408  0.86803315]
 [0.48633985 0.06797038 0.57261143 0.05834221 1.        ]
 [0.71798764 0.30971557 0.70224379 0.86051799 0.52247748]]


#### 17. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [45]:
a = np.arange(11)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [46]:
a[(3 < a) & (a <= 8)] *= -1
a

array([ 0,  1,  2,  3, -4, -5, -6, -7, -8,  9, 10])

#### 18. How to round away from zero a float array ? (★☆☆)

In [48]:
def round_away(x,y):
    return np.round(x,y)

a = np.array([12.5, 42.67, 5.69, 97.81])

print(round_away(a, 0))

[12. 43.  6. 98.]


#### 19. Find common values between two arrays? (★☆☆)

In [50]:
a = np.array([0,1,2,3,4,5,6,7,8,9,10])
print(a)
b = np.array([0,2,4,6,8,10])
print(b)
print('The common values between the two arrays are:')
print(np.intersect1d(a, b))

[ 0  1  2  3  4  5  6  7  8  9 10]
[ 0  2  4  6  8 10]
The common values between the two arrays are:
[ 0  2  4  6  8 10]


#### 20. Is the following expressions true? (★☆☆)

```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

After looking up np.emath.sqrt(), no, the expression is not true. 
np.sqrt(-1) = NaN while np.emath.sqrt(-1) returns a complex value.

In [51]:
np.sqrt(-1)

C:\Users\opera\AppData\Local\Temp\ipykernel_11804\3438155168.py:1: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(-1)


nan

In [52]:
np.emath.sqrt(-1)

1j

#### 21. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [55]:
def generator():
    for x in range(10):
        yield x

a = np.fromiter(generator(), dtype = int)
print(a)

[0 1 2 3 4 5 6 7 8 9]


#### 22. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [60]:
a = np.linspace(0,1,12)[1: -1]
print(a)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


#### 23. Create a random vector of size 10 and sort it (★★☆)

In [61]:
a = np.random.random(10)
print(a)
a.sort()
print(a)

[0.30309673 0.85001673 0.57757151 0.37818376 0.25491839 0.12865618
 0.45839235 0.77277724 0.86315591 0.55963864]
[0.12865618 0.25491839 0.30309673 0.37818376 0.45839235 0.55963864
 0.57757151 0.77277724 0.85001673 0.86315591]


#### 24. Consider two random arrays A and B, check if they are equal (★★☆)

In [63]:
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)
equal = np.allclose(A,B)
print(equal)

False


#### 25. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [64]:
a = np.random.random(10)
print(a)
a[a.argmax()] = 0
print(a)

[0.00362218 0.37728786 0.66323967 0.66861193 0.85172985 0.93859862
 0.66499867 0.58736447 0.84751316 0.31830069]
[0.00362218 0.37728786 0.66323967 0.66861193 0.85172985 0.
 0.66499867 0.58736447 0.84751316 0.31830069]


#### 26. Find the closest value to random element in a vector? (★★☆)

In [65]:
# This one has me a bit confused
a = np.arange(100)
print(a)
b = np.random.uniform(0,100)
print(b)
index = (np.abs(a - b)).argmin()
print(a[index])

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]
61.24258844156301
61


#### 27. Convert a float (32 bits) array into an integer (32 bits) in place?

In [66]:
float_array = np.array([1.2, 3.5, 5.1])
print(float_array)
integer_array = np.array(float_array, dtype = 'int32')
print(integer_array)

[1.2 3.5 5.1]
[1 3 5]


#### 28. Sort an array by the nth column? (★★☆)

In [67]:
a = np.random.randint(0,10,(3,3))
print(a)
print(a[a[:,1].argsort()])

[[4 6 7]
 [3 3 2]
 [5 8 8]]
[[3 3 2]
 [4 6 7]
 [5 8 8]]


#### 29. Find if a given 2D array has null (empty) columns? (★★☆)

In [68]:
a = np.random.randint(0,3,(4,10))
print(a)
print((~a.any(axis = 0)).any())

[[1 0 1 0 1 1 1 1 1 1]
 [2 1 1 2 0 2 2 2 1 1]
 [1 0 2 0 0 0 0 2 1 1]
 [0 2 1 2 2 1 1 1 1 0]]
False


#### 30. Consider the vector \[1, 2, 3, 4, 5\], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

In [69]:
a = np.array([1,2,3,4,5])
na = 3
a0 = np.zeros(len(a) + (len(a) - 1) * (na))
a0[::na + 1] = a
print(a0)

[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


#### 31. Swap two rows of an array? (★★★)

In [71]:
a = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
print(a)
a[[0,2]] = a[[2,0]]
print(a)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[ 7  8  9]
 [ 4  5  6]
 [ 1  2  3]
 [10 11 12]]


#### 32. How to negate a boolean value inside an array? (★★★)

In [ ]:
# Cannot figure this one out, or find anything that clicked with me on Google...

#### 33. Find the most frequent value in an array?

In [72]:
a = np.random.randint(0, 10, 40)
print(a)
print(np.bincount(a).argmax())

[7 4 6 6 3 7 4 6 1 4 1 9 7 6 4 4 4 2 2 0 5 2 5 9 0 7 8 0 9 1 8 4 1 4 8 9 1
 9 2 1]
4


#### 34. Get the n largest values of an array (★★★)

In [73]:
a = np.arange(10)
print(a)
np.random.shuffle(a)
n = 1
print(a[np.argsort(a)[-n:]])

[0 1 2 3 4 5 6 7 8 9]
[9]


#### 35. Extract unique rows from a two dimensional array? (★★★)

In [78]:
a = np.array([[1,1,1,0,0,0],
             [0,1,1,1,0,0],
             [0,1,1,1,0,0],
             [1,1,1,0,0,0],
             [1,1,1,1,1,0]])
print(a)
print(np.unique(a, axis = 0))

[[1 1 1 0 0 0]
 [0 1 1 1 0 0]
 [0 1 1 1 0 0]
 [1 1 1 0 0 0]
 [1 1 1 1 1 0]]
[[0 1 1 1 0 0]
 [1 1 1 0 0 0]
 [1 1 1 1 1 0]]
